services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=monopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/monogdb/data
volumes:
  pgdata:
  mongodata:
