services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/data
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=monopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/monogdb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  svc-auction:
    image: b3cecchini/svc-auction:latest
    build:
      context: .
      dockerfile: src/svc-auction/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=POSTGRES_PASSWORD;Database=autcions
      - IdentityServiceUrl=http://svc-identity
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  svc-search:
    image: b3cecchini/svc-search:latest
    build:
      context: .
      dockerfile: src/svc-search/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:monopw@mongo
      - AuctionServiceUrl=http://svc-auction
    ports:
      - 7002:80
    depends_on:
      - mongo
      - rabbitmq
  svc-identity:
    image: b3cecchini/svc-identity:latest
    build:
      context: .
      dockerfile: src/svc-identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=POSTGRES_PASSWORD;Database=identity
      - AuctionServiceUrl=http://svc-auction
    ports:
      - 5000:80
    depends_on:
      - postgres
  svc-gateway:
    image: b3cecchini/svc-gateway:latest
    build:
      context: .
      dockerfile: src/svc-gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
